import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Providers from './providers';
import type { Locales } from '@/types/locales';

import './globals.css';

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'es' }];
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'React Hello World | Enterprise Edition',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    lang: Locales;
  };
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
